export const FETCH_ALL='FETCH_ALL'
export const CREATE='CREATE'
export const DELETE='DELETE'
export const UPDATE='UPDATE'
export const FETCH_USER_POST='FETCH_USER_POST'
export const LIKE ='LIKE'
export const GET_USER='GET_USER'
export const FETCH_USER_NOTIFICATIONS='FETCH_USER_NOTIFICATIONS'
export const UPDATE_DESCRIPTION='UPDATE_DESCRIPTION'
export const USER_NOT_FOUND='USER_NOT_FOUND'
export const FOLLOW_REQUEST='FOLLOW_REQUEST'
export const FOLLOW='FOLLOW'
export const FETCH_MORE='FETCH_MORE'
export const GET_USERS='GET_USERS'
export const NO_DATA='NO_DATA'
export const DELETE_NOTIFICATION='DELETE_NOTIFICATION'
export const DELETE_MESSAGE_NOTIFICATION='DELETE_MESSAGE_NOTIFICATION'
export const SEARCH_USER='SEARCH_USER'
export const GET_CONVERSATIONS='GET_CONVERSATIONS'
export const NEW_NOTIFICATION='NEW_NOTIFICATION'
export const GET_NOTIFICATIONS='GET_NOTIFICATIONS'
export const CREATE_CONVERSATION='CREATE_CONVERSATION'
export const AUTH = 'AUTH';
export const AUTH_FAIL='AUTH_FAIL'
export const SIGNIN_FAIL='SIGNIN_FAIL'
export const LOGOUT = 'LOGOUT';

export const GET_USER_POST="GET_USER_POST"
export const LIKE_USER_POST="LIKE_USER_POST"
export const DISLIKE_USER_POST="DISLIKE_USER_POST"
export const COMMENT_USER_POST="COMMENT_USER_POST"
export const DELETE_USER_PROFILE_COMMENT="DELETE_USER_PROFILE_COMMENT"
export const LIKE_USER_POST_COMMENT="LIKE_USER_POST_COMMENT"
export const  LIKE_USER_PROFILE_COMMENT=" LIKE_USER_PROFILE_COMMENT"








